### PR TITLE
#20: Allow string args in log template function

### LINKED ISSUE #20: Allow for formatting strings
Compilation Error:

```
logger_impl.hpp:139:40: error: no matching function for call to ‘to_string(std::__cxx11::basic_string<char>&)’
139 | ((oss << " " << std::to_string(args) << "\n"), ...);
```

Caused by attempting to format a string, e.g.

```cpp
std::string myString = "hello";
PRESSIOLOG_INFO("{}," myString);
```

Possible solution:

Instead of hard-coding `std::to_string(args)` (which fails when an argument is already a string), create a custom`to_string` wrapper that determines if an argument is a string or not before attempting to convert.

We need to make sure this use case is covered by the unit testing.

### PR DESCRIPTION
**Pull request by chadalon**
I simply removed the ```std::to_string()``` call when printing out the arguments given an error. The ostringstream ```<<``` operator already handles strings, numeric types, and most other types, so we don't need to convert the args anyway.

### CODE REVIEW

File: include/pressio-log/logger/logger_impl.hpp [hunk 1]
```diff
@@ -136,7 +136,7 @@ inline void Logger::log(LogLevel level, const std::string& fmt_str, Args&&... ar
     } catch(const fmt::v11::format_error&) {
         std::ostringstream oss;
         oss << "fmt could not format given string: " << fmt_str << " with args:\n";
-        ((oss << "  " << std::to_string(args) << "\n"), ...);
+        ((oss << "  " << args << "\n"), ...);
```
Comment (cwschilly) [inline include/pressio-log/logger/logger_impl.hpp:139]: This is a good fix, but I'm not sure it solves the root problem.

This change is in the `catch` block that handles the case when the `fmt::format(...)` call above fails. We need to fix it so that the `try` block succeeds when there is a `std::string` in `args`.

Your test may be passing because `CoutRedirector` is capturing the error message that includes the args--so `check_output()` does find the string in the output.

To make sure that's not happening, you could add a check to the test to make sure that we're not throwing the error. Maybe something like:

```cpp
EXPECT_TRUE(check_output(output, "could not format given string",   false));
```

Let me know if this makes sense.

File: tests/logging/test_logger_string.cc [hunk 2]
```diff
@@ -0,0 +1,25 @@
+#include <gtest/gtest.h>
+
+#include "helpers.hpp"
+#include "LoggerTest.hpp"
+#include "pressio-log/core.hpp"
+
+TEST_F(LoggerTest, Logger_String_Templated) {
```
Comment (cwschilly) [inline tests/logging/test_logger_string.cc]: Since we test the individual log levels in a separate unit test, we don't need to run through them all here (they all call the same logging function, so if the formatting works for one, it'll work for them all).

Just pick one level (i.e. `SPARSE`) and run through some of the permutations you have here (one string, two strings, number and a string).

**Review by cwschilly — CHANGES_REQUESTED** [review]
Looks good; just requesting some changes to the unit test to simplify and confirm everything works

File: tests/logging/test_logger_string.cc (hunk 2 above)
Comment (cwschilly) [inline tests/logging/test_logger_string.cc]: Also: I suggest you rename the test `Logger_String_Formatting`  instead of `Templated` just to be a little more clear what we're testing

Comment (chadalon) [reply tests/logging/test_logger_string.cc]: Changed this to use sparse level for each log.

Comment (chadalon) [reply tests/logging/test_logger_string.cc]: Renamed test to suggestion

File: include/pressio-log/logger/logger_impl.hpp (hunk 1 above)
Comment (chadalon) [reply include/pressio-log/logger/logger_impl.hpp:139]: Just leaving a documented trail here: As we discussed, it turns out this was a compile-time problem. ```to_string()``` has no overload for a string parameter, and we can just use the ```ostringstream``` ```operator<<``` since it handles both strings and numeric types.

**Review by cwschilly — APPROVED** [review]
