### PR TITLE
#9: Fix bug in `std::call_once`

### LINKED ISSUE #9: `Unknown error -1` thrown by `std::call_once`
Encountered on RHEL8 with gcc-8 and gcc-13.

Error message:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
```

Full backtrace:

```
#0  0x00007ffff711652f in raise () from /lib64/libc.so.6
#1  0x00007ffff70e9e65 in abort () from /lib64/libc.so.6
#2  0x00007ffff7ac809b in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] () from /lib64/libstdc++.so.6
#3  0x00007ffff7ace54c in __cxxabiv1::__terminate(void (*)()) () from /lib64/libstdc++.so.6
#4  0x00007ffff7ace5a7 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff7ace808 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007ffff7aca235 in std::__throw_system_error(int) [clone .cold.28] () from /lib64/libstdc++.so.6
#7  0x0000000000419f6b in std::call_once<pressiolog::Logger::initialize(pressiolog::LogLevel, pressiolog::LogTo, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}>(std::once_flag&, pressiolog::Logger::initialize(pressiolog::LogLevel, pressiolog::LogTo, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}&&) (__once=..., __f=...)
    at /usr/include/c++/8/mutex:692
#8  0x0000000000411d5c in pressiolog::Logger::initialize (this=0x993d80, level=pressiolog::LogLevel::info, destination=pressiolog::LogTo::file, filename="log.txt")
    at /home/crwentl/research/code/pressio-proj/pressio-log/include/pressio-log/logger/logger_impl.hpp:66
#9  0x000000000043110d in run_mono_fom<pressiodemoapps::PublicProblemEigenMixinCpp<pressiodemoapps::impladvdiff2d::EigenApp<pressiodemoapps::impl::CellCenteredUniformMesh<double, int, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, -1, 1, -1, -1>, false>, pressiodemoapps::impl::NoOperation<void> > >, Parser2DBurgers<double> > (system=..., parser=...) at /home/crwentl/research/code/pressio-proj/pdas-experiments/include/pdas-exp/mono_fom.hpp:13
#10 0x000000000041da9e in dispatch_mono<pressiodemoapps::PublicProblemEigenMixinCpp<pressiodemoapps::impladvdiff2d::EigenApp<pressiodemoapps::impl::CellCenteredUniformMesh<double, int, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, -1, 1, -1, -1>, false>, pressiodemoapps::impl::NoOperation<void> > >, Parser2DBurgers<double> > (fomSystem=..., parser=...) at /home/crwentl/research/code/pressio-proj/pdas-experiments/src/runner.cc:16
#11 0x000000000040aa5a in main (argc=2, argv=0x7fffffffcee8) at /home/crwentl/research/code/pressio-proj/pdas-experiments/src/runner.cc:120
```

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #9 

For now, this only cleans up initialization and adds a warning in the README about the bug. I've created #15 as a follow-on to ensure that the logger works even when threading is not enabled by the compiler.

### CODE REVIEW

File: include/pressio-log/logger/logger_impl.hpp [hunk 1]
```diff
@@ -93,7 +94,12 @@ inline void Logger::initializeWithMPI(
 #endif
 
 inline void Logger::finalize() {
+    std::unique_lock<std::mutex> lock(init_mutex_);
     log(LogLevel::info, colors::green("pressio-log finalized."));
+    setLoggingLevel(LogLevel::none);
+    logger_is_initialized_.store(false, std::memory_order_release);
+    init_flag_ = std::make_unique<std::once_flag>();
+    init_warning_flag_ = std::make_unique<std::once_flag>();
```
Comment (cwschilly) [inline include/pressio-log/logger/logger_impl.hpp:102]: These lines allow a user to initialize the logger again after it has been finalized (e.g. for testing purposes).

**Review by fnrizzi — APPROVED** [review]
